apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-api
  name: location-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-api
  name: location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-api
  template:
    metadata:
      labels:
        service: location-api
    spec:
      containers:
      - image: bhatsubhas/location-api:latest
        name: location-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_PORT
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
        - name: LOCATION_GRPC_HOST
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: LOCATION_GRPC_HOST
        - name: LOCATION_GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: grpc-env
              key: LOCATION_GRPC_PORT
      restartPolicy: Always
